#ifndef OXC_OPERATOR_H
#define OXC_OPERATOR_H

#include <map>
#include <string>

namespace Node {
  enum Operator {
    PUNCTUATION_COLON,
    PUNCTUATION_COMMA,
    PUNCTUATION_DIVISION_SIGN,
    PUNCTUATION_GREATER_THAN_OR_EQUAL_TO,
    PUNCTUATION_GREATER_THAN_SIGN,
    PUNCTUATION_LEFT_CURLY_BRACKET,
    PUNCTUATION_LEFT_PARENTHESIS,
    PUNCTUATION_LEFT_SQUARE_BRACKET,
    PUNCTUATION_LEFTWARDS_ARROW,
    PUNCTUATION_LESS_THAN_OR_EQUAL_TO,
    PUNCTUATION_LESS_THAN_SIGN,
    PUNCTUATION_MINUS_SIGN,
    PUNCTUATION_MULTIPLICATION_SIGN,
    PUNCTUATION_PLUS_SIGN,
    PUNCTUATION_RIGHT_CURLY_BRACKET,
    PUNCTUATION_RIGHT_PARENTHESIS,
    PUNCTUATION_RIGHT_SQUARE_BRACKET,
    PUNCTUATION_RIGHTWARDS_ARROW,
    PUNCTUATION_SEMICOLON
  };
}

#endif
